travis:
  secure:
    BINSTAR_TOKEN: f2dV0f8j+opy7y9PLovEUV3EN4XsOpw9zyLGrdMJelmq6QvgPF1FwtzONB08TwOePtfGappKTst4d5DrderVekW4F3j1HZJotFVmgs99Y6OKK1uugDsIE4KHGHeIEA2s7HKI7IrCwhySl3TWbsMTJKx9yHH/WC0fB6NIrTtynXzQdIQwSsncZLU/yLqoCvPXH3jHArsHvXQhPHcD6v4LjqSk+vOJcbE6vQPo4tLFbDCAWifynd8m4aWMRyLXCqCJzEFyZx1CrX0LXN6LUEa9OIKyWgDeO/ka7V8K6x0ydKJPtBx+LOkmD8Uhg2qF+B2To9xDWO24FDZQ/nKcopt+hblqGtge6Kli2ruM2dfRfpkVI+BDTzjzTk2d52sn7zKOWDbWiVmz/ncmvY3RpGQz+tPnovqk1zyfisZd9rAfJxzsqnn7enfGRpYPtUXY1hBJaC1vim9lnLyAtE7oxjMqEQcRiwt3L3ARBINc10+WVaUdL0sg/sprPQCnjZtNjbakPZpMvIsY/A5AZC+a4EvMONNuBogbnfbJijfO8QcIqDuY5xvOdOA4tfbEfExoedIf+GxAZNNhg511WHNuUprwx32w9M2kD78bwIobL8IsIfJYlC1Y/nfNK0wIA3oshgf5pA+EuU9ZfC8s9hx53DEIiozgIBDT5gTt1Y9lOhTzxzg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
